# Generated by Django 4.0.3 on 2022-04-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
        ('store', '0003_auto_20220410_1110'),
    ]

    operations = [
    ]
